fea/make main page using chakra and routing
Guilherme-BS/blog-next pull request #1
Opened 2022-05-28 16:11 UTC by Guilherme-BS

## Description 

> Chakra was used as the main source of stylization, and a dynamic pagination of the next
![Captura de tela de 2022-05-28 13-08-57](https://user-images.githubusercontent.com/73261443/170833501-469d7d39-4936-498a-8f74-5d1c251b2fea.png)

2022-05-31 00:10 UTC, vzsoares reviewed
só detalizinhos msm ... show!!

2022-05-31 00:10 UTC, vzsoares commented on componentes/App.tsx
> +import { dataPost } from "../utils/data-post";
essa variavel pra fazer sentido seria 
```suggestion
import { postsData } from "../utils/data-post";
```

2022-05-31 00:10 UTC, vzsoares commented on componentes/App.tsx
> +        {dataPost.map((data) => (
seguindo a logica poderia ser entao 

```suggestion
        {dataPost.map((postData) => (
```
ou só `data` msm

2022-05-31 00:10 UTC, vzsoares commented on componentes/Post.tsx
> +interface dataP {
dataP ?

2022-05-31 00:10 UTC, vzsoares commented on componentes/Post.tsx
> +export default function Post({ data }: dataP) {
poderia desestruturar as variáveis aq direto para deixar mais limpo o codigo

sugestao https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#desestrutura%C3%A7%C3%A3o_de_objeto

2022-05-31 00:10 UTC, vzsoares commented on pages/[post].tsx
> +  const post = dataPost.find((p) => String(p.id) === postId);
aq tmb da pra desestruturar 
```suggestion
  const {title, imgUrl, text} = dataPost.find((p) => String(p.id) === postId);
```

2022-05-31 00:10 UTC, vzsoares commented on componentes/App.tsx
> +}
obs: ja tem um _app.tsx e um index.tsx se essa aq é sua main page acho  q poderia ficar no index.tsx msm

2022-05-31 00:10 UTC, vzsoares commented on componentes/App.tsx
> +    <div>
como essa div esta só envolvendo o componente e nao possui nenhum atributo vc pode deixar vazio
```suggestion
    <>
```

https://pt-br.reactjs.org/docs/fragments.html#short-syntax

2022-05-31 00:10 UTC, vzsoares commented on componentes/Post.tsx
> +      <a>
nesse caso pq tem esse <a> se já tem um Link em cima q é a msm coisa?

2022-05-31 13:59 UTC, marco-souza commented on componentes/App.tsx
> +import { dataPost } from "../utils/data-post";
ai tem que mudar o nome do arquivo tbm

2022-05-31 13:59 UTC, marco-souza commented on componentes/Post.tsx
> +interface dataP {
Acho que precisamos de nomes mais significativos para os tipos usados

2022-05-31 14:00 UTC, marco-souza commented on pages/[post].tsx
> +  const post = dataPost.find((p) => String(p.id) === postId);
Vale lembrar que find pode retornar null

2022-05-31 14:00 UTC, marco-souza commented on componentes/App.tsx
> +}
Boa! Ou poderia chamar esse componente/arquivo de `Home` ou `HomePage`

2022-05-31 14:01 UTC, marco-souza commented on componentes/Post.tsx
> +      <a>
eh, me parece duplicado esse a, dado que o `Link` ja eh um `a` por debaixo dos panos

2022-05-31 14:10 UTC, marco-souza requested changes
Boa mano! Acho que faltou usar melhor os components do Chakra. 
Em geral, quando usamos chakra, evitamos qualquer tipo de componente nativo do html (div, h1, p, span...), pois a lib do chakra tem todos esses componentes estilizados e pronto pra uso.

Recomendo dar uma revisada nisso.

2022-05-31 14:10 UTC, marco-souza commented on componentes/App.tsx
> +    <div>
Na real poderia ate ser removida ne, dado que so tem um componente como filho

2022-05-31 14:10 UTC, marco-souza commented on componentes/App.tsx
> +          <Post data={data} />
kd a  `key`?

2022-05-31 14:10 UTC, marco-souza commented on componentes/Post.tsx
> +export default function Post({ data }: dataP) {
```suggestion
}

export default function Post({ data }: dataP) {
```

2022-05-31 14:10 UTC, marco-souza commented on componentes/Post.tsx
> +            <Box display="flex" mt="2" alignItems="center"></Box>
pq temos essas boxes bazias?

2022-05-31 14:10 UTC, marco-souza commented on componentes/Post.tsx
> +              ></Box>
Pq isso ta aqui sem nenhum filho dentro?

2022-05-31 14:10 UTC, marco-souza commented on pages/[post].tsx
> +  const post = dataPost.find((p) => String(p.id) === postId);
Acho inclusive que eh por isso que ele não fez o destructuring aqui, senao ele nao teria como checar

2022-05-31 14:10 UTC, marco-souza commented on pages/_app.tsx
> +  );
identação

2022-05-31 14:10 UTC, marco-souza commented on pages/[post].tsx
> +      <p>{post.text}</p>
quando estamos usando chakra, evitamos usar elementos nativo do html. Temos componentes para imagens e textos (Text, Image) dentro do chakra

2022-05-31 14:10 UTC, marco-souza commented on pages/[post].tsx
> +    <div>
precisamos dessa div? Se sim, recomendo usar Box do chakra

2022-05-31 14:10 UTC, marco-souza commented on pages/index.tsx
> +    <div>
waa div nao poderia ser removida? Não parece ta fazendo nada

2022-05-31 19:54 UTC, Guilherme-BS commented on componentes/Post.tsx
> +interface dataP {
coloquei pra testar se ia funcionar, esqueci de corrigir muita coisa nesse codigo antes de abrir o pr

2022-06-01 01:24 UTC, vzsoares requested changes
acho q vale mais uma lida no chrakra
![image](https://user-images.githubusercontent.com/86134825/171308890-91bf2877-f0e1-4f7c-9249-e1907c312a44.png)
podia fazer ter apenas um card em tela pequena por exemplo ... tambem como mudar tamanho do titulo.

sugestao: https://chakra-ui.com/docs/styled-system/features/responsive-styles

> tambem faltou o botao de `back` (voltar para main page) dentro dos posts

2022-06-01 12:05 UTC, marco-souza commented on componentes/NavBar.tsx
> +      padding="0.5em"
`em` eh uma medida relativa ao tamanho da font do elemento pai, `rem` eh uma medida relativa ao tamanho da font da pagina

2022-06-01 12:05 UTC, marco-souza commented on componentes/Post.tsx
> +interface dataType {
tipos e classes começam com letras maiusculas.

Tbm vale a pena usar um nome mais especifico que data

```suggestion
interface PostProps {
```

2022-06-01 12:05 UTC, marco-souza commented on componentes/Post.tsx
> +          {text}
```suggestion
          <Text>{text}</Text>
```

2022-06-01 12:05 UTC, marco-souza commented on pages/[post].tsx
> +  const post = postData.find((p) => String(p.id) === postId);
```suggestion
  const post = postData.find(({ id }) => String(id) === postId);
```

2022-06-01 12:05 UTC, marco-souza commented on pages/[post].tsx
> +  if (postId == null) return <p>Loading...</p>;
```suggestion
  if (postId == null) return <Text>Loading...</Text>;
```

2022-06-01 12:05 UTC, marco-souza commented on pages/[post].tsx
> +  if (post == null) return <p>Not found</p>;
```suggestion
  if (post == null) return <Text>Not found</Text>;
```

2022-06-06 11:09 UTC, Filipe-barbosa commented on componentes/Post.tsx
> +          {text}
talvez fosse legal dar outro nome a esta variavel, algo nao tao generico como text

2022-06-06 11:09 UTC, Filipe-barbosa commented on pages/[post].tsx
> +  if (postId == null) return <p>Loading...</p>;
tambem uma comparação  com tipo e valor não  seria algo mais seguro ?

2022-06-06 11:09 UTC, Filipe-barbosa commented on utils/post-data.ts
> +export const postData = [
e se invés  de exportar esta constante, consumíssemos  ela como um json. o que acha ?

2022-06-09 19:47 UTC, vzsoares approved these changes

2022-06-09 19:47 UTC, vzsoares commented on pages/api/hello.ts
>  }
you probably could just delete this file

2022-06-09 19:47 UTC, vzsoares commented on componentes/HomePage.tsx
> +      <SimpleGrid gap={6} columns={{ sm: 1, md: 2, lg: 3 }}>
now that's more like it !!

2022-06-09 19:47 UTC, vzsoares commented on componentes/NavBar.tsx
> +      <Text fontSize={{ base: "30px", md: "45px", lg: "60px" }}>
is it real necessary to have a <Text inside a <Heading ?

2022-06-09 19:47 UTC, vzsoares commented on pages/[post].tsx
>  export default function PostOne() {
`PostOne` means `Primeiro Post` on the other hand `OnePost` means `Um Post (um post qualquer)`

2022-06-12 16:18 UTC, marco-souza approved these changes

2022-06-13 18:19 UTC, merged